version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - "3001:3001"
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb-primary
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  url-shortener:
    build:
      context: .
      dockerfile: ./apps/url-shortener/Dockerfile
      target: development
    command: npm run start:dev url-shortener
    ports:
      - "3000:3000"
    env_file:
      - ./apps/url-shortener/.env
    depends_on:
      - mongodb-primary
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb-primary:
    image: mongo:latest
    platform: ${DOCKER_PLATFORM:-linux/arm64/v8}
    container_name: url-shortener-mongodb-primary
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_master_data:/data/db

volumes:
  mongodb_master_data:
    driver: local
